import { Tree } from '@nx/devkit';

export interface VueRouteSpec {
  path: string;
  /** Relative import path passed to () => import(...), e.g. '../views/FooView.vue'. */
  componentImportPath: string;
  requiresAuth?: boolean;
}

// Deterministic text insertion, not an AST edit -- vue-app's router/index.ts
// template has a fixed `routes: [ ... ]` shape, so a targeted anchor is
// simpler and safer here than pulling in an AST library for one array entry.
export function insertVueRoute(
  host: Tree,
  projectRoot: string,
  project: string,
  route: VueRouteSpec,
): void {
  const routerPath = `${projectRoot}/src/router/index.ts`;
  const content = host.read(routerPath)?.toString();
  if (content === undefined) {
    throw new Error(
      `Could not find ${routerPath} -- is "${project}" a vue-app project generated by @abgov/nx-adsp:vue-app?`,
    );
  }

  const marker = 'routes: [';
  const markerIndex = content.indexOf(marker);
  if (markerIndex === -1) {
    throw new Error(
      `Could not find "${marker}" in ${routerPath} -- has its shape changed since @abgov/nx-adsp:vue-app generated it?`,
    );
  }

  const metaLine = route.requiresAuth
    ? `\n      meta: { requiresAuth: true },`
    : '';
  const routeSnippet =
    `{\n` +
    `      path: '${route.path}',\n` +
    `      component: () => import('${route.componentImportPath}'),${metaLine}\n` +
    `    },`;

  const insertAt = markerIndex + marker.length;
  const updated =
    content.slice(0, insertAt) +
    `\n    ${routeSnippet}` +
    content.slice(insertAt);
  host.write(routerPath, updated);
}
