# This is a basic workflow to help you get started with Actions

name: Release CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      - beta

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci
      - name: Get last successful commit
        id: last_successful_commit
        uses: nrwl/nx-set-shas@v3
      - name: Lint
        run: npm run affected:lint -- --base=${{ steps.last_successful_commit.outputs.base }}
      - name: Test
        run: npm run affected:test -- --base=${{ steps.last_successful_commit.outputs.base }} --verbose
      - name: Build
        run: npm run affected:build -- --base=${{ steps.last_successful_commit.outputs.base }}
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx nx affected --target release --base=${{ steps.last_successful_commit.outputs.base }}
